# Generated by Django 5.0.3 on 2026-09-04 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='الرصيد المتاح')),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='الرصيد المعلق')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'محفظة',
                'verbose_name_plural': 'المحافظ',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('transaction_type', models.CharField(choices=[('deposit', 'إيداع / شحن رصيد'), ('purchase', 'خصم / شراء خدمة'), ('commission', 'إضافة عمولة تسويق'), ('refund', 'استرجاع رصيد')], max_length=20, verbose_name='نوع المعاملة')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول / مكتمل'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة المعاملة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='تفاصيل / ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المعاملة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حركة مالية',
                'verbose_name_plural': 'سجل الحركات المالية',
            },
        ),
    ]
