# Generated by Django 5.0.3 on 2026-09-04 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم القسم')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف القسم')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/icons/', verbose_name='أيقونة القسم')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الخدمة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الخدمة')),
                ('provider_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='تكلفة المزود')),
                ('price', models.DecimalField(decimal_places=2, help_text='السعر الذي يظهر للعميل (سعر البيع)', max_digits=10, verbose_name='السعر للعميل')),
                ('base_quantity', models.PositiveIntegerField(default=1000, help_text='مثال: السعر أعلاه لكل 1000 وحدة', verbose_name='الكمية الأساسية')),
                ('min_quantity', models.PositiveIntegerField(default=10, verbose_name='الحد الأدنى للطلب')),
                ('max_quantity', models.PositiveIntegerField(default=100000, verbose_name='الحد الأقصى للطلب')),
                ('provider_service_id', models.CharField(blank=True, help_text='ID الخدمة في موقع المزود (للربط التلقائي)', max_length=100, null=True, verbose_name='Provider Service ID')),
                ('status', models.CharField(choices=[('active', 'متاحة'), ('inactive', 'غير متاحة')], default='active', max_length=20, verbose_name='حالة الخدمة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.category', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
            },
        ),
    ]
