# Generated by Django 5.0.3 on 2026-09-04 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500, verbose_name='الرابط (Link)')),
                ('quantity', models.PositiveIntegerField(verbose_name='العدد المطلوب')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي التكلفة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'جاري التنفيذ'), ('in_progress', 'قيد العمل'), ('completed', 'مكتمل'), ('partial', 'مكتمل جزئياً'), ('cancelled', 'ملغى'), ('refunded', 'مسترجع')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('provider_order_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم طلب المزود (API ID)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='services.service', verbose_name='الخدمة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='العميل/المسوق')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
    ]
