# Generated by Django 5.0.3 on 2026-09-05 02:04

import django.db.models.deletion
import marketers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(default=marketers.models.generate_referral_code, max_length=20, unique=True, verbose_name='كود الإحالة')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='النسبة المئوية (مثال: 5.00 تعني 5%)', max_digits=5, verbose_name='نسبة العمولة (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketer_account_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف مسوق',
                'verbose_name_plural': 'ملفات المسوقين',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('marketer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='marketers.marketerprofile', verbose_name='المسوق')),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invited_by_marketer', to=settings.AUTH_USER_MODEL, verbose_name='العميل المُحال')),
            ],
            options={
                'verbose_name': 'إحالة',
                'verbose_name_plural': 'سجل الإحالات',
            },
        ),
    ]
